### PR TITLE
Workaround for st3 docs

### LINKED ISSUE #2284: https://lsp.readthedocs.io/ 404s
**Describe the bug**
The documentation at https://lsp.readthedocs.io/

**To Reproduce**
1. Go to https://lsp.readthedocs.io/

**Expected behavior**
The documentation for ST3 should load.

### PR DESCRIPTION
**Pull request by predragnikolic**
closes #2284

I try to use the mkdocs-redirect plugin to specify the redirect:
```diff
plugins:
  - search
  - redirects:
      redirect_maps:
        'guides/cplusplus.md': 'https://github.com/sublimelsp/LSP-clangd'
        'guides/client_configuration.md': 'client_configuration.md'
+        'https://lsp.readthedocs.io/en/latest/': 'https://lsp.readthedocs.io/en/stable/'
```
but it didn't work,
so I used JavaScript.

### CODE REVIEW

File: docs/src/js/redirect.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// Fore info see issue: https://github.com/sublimelsp/LSP/issues/2284#issuecomment-1606014439
+if (window.location.toString() === "https://lsp.readthedocs.io/en/latest/") {
+	window.location.href = 'https://lsp.readthedocs.io/en/stable/'
+}
```
Comment (rchl) [inline docs/src/js/redirect.js:4]: What are your thoughts regarding my comment https://github.com/sublimelsp/LSP/issues/2284#issuecomment-1606018873 ?

That documentation doesn't indicate anywhere that it's for ST3 so I don't feel like it's worth making it more accessible. I'd rather redirect to ST4 documentation.

**Review by rchl — APPROVED** [review]
